SIS2/Server/WebMVC/Controllers/AuthController.cs
#nullable enable

using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Supermodel.Persistence.Repository;
using Supermodel.Persistence.UnitOfWork;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Bootstrap4.Models;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using Supermodel.Presentation.Mvc.Extensions;

namespace WebMVC.Controllers
{
    public class AuthController : SimpleAuthController<Bs4.LoginMvcModel>
    {
        #region Overrides
        protected override async Task<List<Claim>> AuthenticateAndGetClaimsAsync(string username, string password)
        {
            await using(new UnitOfWork<DataContext>(ReadOnly.Yes))
            {
                var lowercaseUsername = username.ToLower();
                var user = await LinqRepoFactory.Create<SIS2User>().Items.SingleOrDefaultAsync(x => x.Username.ToLower() == lowercaseUsername);

                if (user != null && user.PasswordEquals(password))
                {
                    var claims = AuthClaimsHelper.CreateNewClaimsListWithIdAndLabel(user.Id, $"{user.FirstName} {user.LastName}");

                    //Add claims for the specific permissions following the example below
                    if (user.Admin) claims.Add(new Claim(ClaimTypes.Role, SIS2User.AdminRole, ClaimValueTypes.String));
                    
                    return claims;
                }
                else
                {
                    return new List<Claim>();
                }
            }        
        }
        protected override IActionResult RedirectToHomeScreen()
        {
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).RemoveControllerSuffix());
        }
        #endregion
    }
}

SIS2/Server/WebMVC/Controllers/ClassController.cs
#nullable enable

using System.Linq;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    [Authorize]
    public class ClassController : CRUDController<Class, ClassMvcModel, DataContext>
    {
        #region Overrides
        protected override IActionResult StayOnDetailScreen(long id)
        {
            return GoToListScreen();
        }
        protected override IQueryable<Class> GetItems()
        {
            return base.GetItems().Include(x => x.StudentsAttended);
        }
        #endregion
    }
}

SIS2/Server/WebMVC/Controllers/SISUserController.cs
#nullable enable

using System.Linq;
using System.Threading.Tasks;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Supermodel.Persistence.Repository;
using Supermodel.Persistence.UnitOfWork;
using Supermodel.Presentation.Mvc.Bootstrap4.D3.Models;
using Supermodel.Presentation.Mvc.Bootstrap4.Models;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    [Authorize]
    [Authorize(Roles = SIS2User.AdminRole)]
    public class SIS2UserController : EnhancedCRUDController<SIS2User, SIS2UserMvcModel, Bs4.SimpleSearchMvcModel, DataContext> 
    { 
        #region Action methods
        [HttpPost]
        public async Task<IActionResult> DeleteToDoItems(long id)
        {
            await using(new UnitOfWork<DataContext>())
            {
                var sis2User = await RepoFactory.Create<SIS2User>().GetByIdAsync(id);
                sis2User.DeleteToDoItems();
            }
            return GoToListScreen();
        }

        public override async Task<IActionResult> List(int? smSkip = null, int? smTake = null, string? smSortBy = null)
        {
            await using(new UnitOfWork<DataContext>(ReadOnly.Yes))
            {
                var sis2Users = await RepoFactory.Create<SIS2User>().GetAllAsync();

                var barChart = new D3.BarChartMvcModel();
                var donutChart = new D3.DonutChartMvcModel();

                foreach (var sis2User in sis2Users)
                {
                    var barDatum = new D3.BarChartMvcModel.Datum(sis2User.Username, sis2User.ToDoItems.Count);
                    barChart.Data.Add(barDatum);

                    var donutDatum = new D3.DonutChartMvcModel.Datum(sis2User.Id, sis2User.Username, sis2User.ToDoItems.Count);
                    donutChart.Data.Add(donutDatum);
                }
                barChart.LabelsNumberFormat = "d";
                barChart.Width = 1500;
                ViewBag.BarChart = barChart;

                ViewBag.DonutChart = donutChart;
            
                return await base.List(smSkip, smTake, smSortBy);
            }
        }
        #endregion
        
        #region Overrides
        protected override IQueryable<SIS2User> ApplySearchBy(IQueryable<SIS2User> items, Bs4.SimpleSearchMvcModel searchBy)
        {
            if (!string.IsNullOrEmpty(searchBy.SearchTerm.Value))
            {
                var searchTermLowerCase = searchBy.SearchTerm.Value.ToLower();
                items = items.Where(x => x.FirstName.ToLower().Contains(searchTermLowerCase) ||
                                         x.LastName.ToLower().Contains(searchTermLowerCase) ||
                                         x.Username.ToLower().Contains(searchTermLowerCase));
            }
            return items;
        }
        protected override IOrderedQueryable<SIS2User> ApplySortBy(IQueryable<SIS2User> items, string? sortBy)
        {
            if (sortBy == "ToDoItem.Count") return items.OrderBy(x => x.ToDoItems.Count);
            if (sortBy == "-ToDoItem.Count") return items.OrderByDescending(x => x.ToDoItems.Count);
            
            if (sortBy == "Address") return items.OrderBy(x => x.Address.Zip);
            if (sortBy == "-Address") return items.OrderByDescending(x => x.Address.Zip);

            return base.ApplySortBy(items, sortBy);
        }
        protected override IQueryable<SIS2User> GetItems()
        {
            return base.GetItems().Include(x => x.SIS2UserPicture);
        }
        protected override IActionResult StayOnDetailScreen(long id)
        {
            return GoToListScreen();
        }
        #endregion
    }
}

SIS2/Server/WebMVC/Controllers/ToDoItemController.cs
#nullable enable

using System.Linq;
using Domain.Entities;
using Domain.Supermodel.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Supermodel.Presentation.Mvc.Auth;
using Supermodel.Presentation.Mvc.Controllers.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    [Authorize]
    public class ToDoItemController : CRUDController<ToDoItem, ToDoItemMvcModel, DataContext>
    {
        #region Overrides
        protected override IActionResult StayOnDetailScreen(long id)
        {
            return GoToListScreen();
        }
        protected override IQueryable<ToDoItem> GetItems()
        {
            var userId = UserHelper.GetCurrentUserId();
            return base.GetItems().Where(x => x.SIS2User.Id == userId).OrderBy(x => x.Priority);
        }
        #endregion
    }
}

SIS2/Server/WebMVC/Views/Shared/_EmptyLayout.cshtml
<!doctype html>
<html lang="en">
<head super-bs4-d3-add-meta-and-links>
    <title>SIS2</title>
    <link type="image/x-icon" rel="shortcut icon" href="/images/favicon.ico" />
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body super-bs4-d3-add-scripts>
    <script type="text/javascript" src="~/js/site.js"></script>
    @RenderBody()
</body>
</html>

SIS2/Server/WebMVC/Views/Shared/_EmptyModalLayout.cshtml
@{ Layout = "_EmptyLayout.cshtml"; }

<div id="dialog" class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="background-color: SkyBlue;">
            <div class="modal-body">
                @RenderBody()
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#dialog').modal({ backdrop: 'static', keyboard: false });
    });
</script>

SIS2/Server/WebMVC/Views/Shared/_MasterLayout.cshtml
@{
    Layout = "_EmptyLayout";
}
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="ToDoItem" asp-action="List">My To Do Items</a>
                    <a class="dropdown-item" asp-controller="Professor" asp-action="List">Professors</a>
                    <a class="dropdown-item" asp-controller="Professor2" asp-action="List">Professors #2</a>
                    <a class="dropdown-item" asp-controller="Class" asp-action="List">Classes</a>
                    <a class="dropdown-item" asp-controller="Department" asp-action="List">Departments</a>

                </div>
            </li>
        </ul>
        <ul class="nav-item navbar-nav navbar-right">
            @if (RequestHttpContext.IsCurrentUserInRole(SIS2User.AdminRole))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle active" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="SIS2User" asp-action="List" asp-route-smSkip="0" asp-route-smTake="4" asp-route-smSortBy="LastName,FirstName">Manage Users</a>
                    </div>
                </li>
            }
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome, @RequestHttpContext.CurrentUserLabel
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="SIS2UserUpdatePassword" asp-action="Detail" asp-route-id="@RequestHttpContext.CurrentUserId">Change Password</a>
                    <a class="dropdown-item" asp-controller="Auth" asp-action="LogOut">Sign Out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<br />
<div id="body">
    @RenderBody()
</div>